### ISSUE TITLE
compiling with -soname on mac

### ISSUE THREAD

**Issue by cgorringe** [hzeller/flaschen-taschen#23]
I was making ft-demos and got this error on OSX 10.11.6 (El Capitan)

```
make -C ft/api/lib
c++ -Wall -O3 -I../include -I. -fPIC -c -o udp-flaschen-taschen.o udp-flaschen-taschen.cc
c++ -Wall -O3 -I../include -I. -fPIC -c -o bdf-font.o bdf-font.cc
c++ -Wall -O3 -I../include -I. -fPIC -c -o graphics.o graphics.cc
ar rcs libftclient.a udp-flaschen-taschen.o bdf-font.o graphics.o
g++ -shared -Wl,-soname,libftclient.so.1 -o libftclient.so.1 udp-flaschen-taschen.o bdf-font.o graphics.o
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libftclient.so.1] Error 1
make: *** [ft/api/lib/libftclient.a] Error 2

```

**Comment by hzeller** [comment]
Ok, so what is -soname then in this new version of macos ? I don't have a mac, so you have to find out :)

**Comment by hzeller** [comment]
Did you figure this out Carl ? What do we have to do differently on Mac ?

**Comment by alexdisoza007** [comment]
sorry, i'm working on linux machine

**Comment by nargetdev** [comment]
So strange.  I experienced the same problem with -soname switch on the mac.  I started looking for the switch to change it, never even found it but it started working on it's own.

**Comment by cgorringe** [comment]
`-soname` still causes an `unknown option` error when running `make` on my ft-demos repo on a Mac, which is running make in flaschen-taschen `/api/lib/Makefile`.  Somehow running make a second time in ft-demos will skip it and compile my programs normally, although it still isn't solved.

**Comment by hzeller** [comment]
Can you figure out how to make a shared library on the Mac and if there is an equivalent of soname ? (I don't have access to a Mac, can't try)

**Comment by nargetdev** [comment]
Replacing  `soname` with `install_name` fixes build on os x
