### ISSUE TITLE
Problem flaschen taschen with RGB matrix

### ISSUE THREAD

**Issue by ffqqtv** [hzeller/flaschen-taschen#24]
Thanks about flaschen-taschen library ! it is great . Now , i have 9 module RGB matrix ( 64x32) connecting Pi 3 , I am using flaschen-taschen library to send image and video , but I do not know how to adjust --led-rows=<rows> --led-chain=<chained> --led-parallel=<parallel> --led-brightness=<percent> -C 
https://youtu.be/XVejSbku9Nc

**Comment by hzeller** [comment]
You have 6 LED panels in a row, so you want --led-chain=6. The 32x32 pixel will already work with the default settings (--led-rows=32 --led-parallel=1).

**Comment by hzeller** [comment]
Also, until a few minutes ago, you also had to explicitly make sure to set the geometry on the server side with `-D64x32`. If you do a fresh `git pull`, this will now be automatic.
