### ISSUE TITLE
extending the chain lenth

### ISSUE THREAD

**Issue by alexdisoza007** [hzeller/flaschen-taschen#25]
hi

Great job !.. I'm working  on this project and not able to extend the chain length, (in  rpi-rgb-led-matrix used -c option to extend the chain length) , how to extend the chain length in this project.

Thanks 
Alex

**Comment by hzeller** [comment]
You mean you are using it with the led matrix ? Try `--led-chain` instead of `-c`

**Comment by alexdisoza007** [comment]
Hi, 
I tired with this command `./send-text -h localhost --led-chain=2 --led-rows=32 -f fonts/9x18.bdf "flaschen taschen"` but this error popup `./send-text:` invalid option -- '-'`

Thanks
Alex

**Comment by hzeller** [comment]
the `--led-chain` you need to give on the **server**, as that is running the LED. That server then provides the display you send stuff with clients such as send-text.

The send-text only needs the right size of your display  with `-g192x32` for instance.

**Comment by alexdisoza007** [comment]
Hi. 
Its working , but it is only using only 48x32, but mine is 64x32.

**Comment by hzeller** [comment]
Did you make sure to set the resolution in the client program so that it knows how big of a framebuffer to send ?
```
 ./send-text -g64x32 ...
```

**Comment by alexdisoza007** [comment]
Yes, its  is -g64x32 only , `./send-image -g64x32 -h localhost ../img/spixels-video.jpg`.

**Comment by alexdisoza007** [comment]
yes , its only -g64x32,` ./send-image -g64x32 -h localhost ../img/spixels-video.jpg`
[https://www.youtube.com/watch?v=MgZdQJVqTzA&feature=youtu.be](url)

**Comment by alexdisoza007** [comment]
Hi, 
I got out of that issue by using `-D 64x32` on server side. Thanks for your support.

Thanks
Alex
