### ISSUE TITLE
Not able to display small letters in newly committed code 

### ISSUE THREAD

**Issue by alexdisoza007** [hzeller/flaschen-taschen#26]
Hi,
In text example program , If I give text in small letters it is displaying in capital letters. Is their any other ways to display small letters? 
If I provide more than one text by pipe lining with different offset i am getting flickering problem ,Is it is due to power issue ? please do find the attach  link
[https://www.youtube.com/watch?v=iqwcEEiQQgU&feature=youtu.be](url)

Thanks 
Alex

**Comment by hzeller** [comment]
I suspect you used a font that didn't have lower case characters ?

If you send multiple text on the same layer, they will be 'fighting' each other as you replace the previous pixels with the new pixels. Try sending them on a different layers.
