### ISSUE TITLE
Daemon process 

### ISSUE THREAD

**Issue by alexdisoza007** [hzeller/flaschen-taschen#29]
Hi ,
How to make send-image file as Daemon process ?

Regards 
Alex

**Comment by hzeller** [comment]
If you just send a single image, it exits immediately, so no need for that.
If you want to send an animated gif, why not just send it to the background with the ampersand-feature of your shell ?
  `./send-image foo.gif &`

**Comment by alexdisoza007** [comment]
Hi,
Even using ampersand-feature of shell ,Its not giving control back to command line if i use the image scrolling. It keeps waiting for ctrl+c.

`pi@raspberrypi:~/flaschen-taschen/client $ ./send-image -g128x32+64+0 -s ../img/aaa.ppm -h localhost &
[8] 4944
pi@raspberrypi:~/flaschen-taschen/client $ Read image...
Scale ... 832x32 -> 832x32

`

**Comment by hzeller** [comment]
No, it should just go into the background. You only see the `Read image` and `Scale...` output, which might look a bit confusing, but if you press return, you see that you are back on the shell, and that Ctrl-C does not do anything.

**Comment by alexdisoza007** [comment]
Thanks for the reply but when i write the command in the systemd its throwing an error.
 
`ExecStart=/usr/bin/send-image -g32x32+0+0 -h localhost $IMAGE_PATH/test.ppm & `

I think its waiting for something/action.

**Comment by hzeller** [comment]
I don't know anything about systemd, so you have to read the documentation how you make stuff there to a daemon. It is meant to do such things, so this should be straightforward.
(I am still using System-V init because systemd configuration is too confusing for me, so I can't help here, sorry).

**Comment by hzeller** [comment]
I guess you figured it out ?
