### ISSUE TITLE
.bdf file not working in flaschen-taschen

### ISSUE THREAD

**Issue by ghost** [hzeller/flaschen-taschen#30]
Hi,

With reference to the issue number #323 of rpi-rgb-led-matrix. Can u fix the bug in it through which we can run .bdf files in flaschen-taschen ?

Thanks and Regards,
Anirban Neogi

**Comment by hzeller** [comment]
Do you have an example font file that exhibits the problem ?

**Comment by ghost** [comment]
https://drive.google.com/open?id=0BztprZbZcrLGVTFnamxLRExfWmM

You can download the font from the above link. The above font works fine with rpi-rgb-led-matrix but it does not work with flaschen-taschen.

**Comment by hzeller** [comment]
I have now fixed FlaschenTaschen code to deal with proportinal fonts, e.g. the `fonts/helvR12.bdf` in this distribution.

(The above file is a spline font format, not BDF @Anrban , but I could reproduce and fix the issue with the helvR12 file).
