### ISSUE TITLE
Diffrent scan rates 

### ISSUE THREAD

**Issue by noorabrar1** [hzeller/flaschen-taschen#35]
Hello sir,

I am new to git hub..

I'm working on HUB75 for a project, the connectivity with pi3, and i am using your client server code.
using 3 different scan rate HUB75 board each four 32x32 panel connected in series and parallel

code:

Server: sudo ./ft-server --led-parallel=2 --led-rows=64 -D64x64 --led-chain=2

Client: sudo ./send-text -g64X64+0-0+1 -h localhost "hello" -f fonts/6x12.bdf -c ff0000

    HUB75-P5-16S-32x32-B0 consist of ABCD data lines (Works absolutely fine with series and parallel connections)

    HUB75-P2.5-32S-64X64 consist of additional E data line, wiring is properly connected(Not working properly, some set of upper led wont glow even i made correction -D128x128)

    HUB75-P5-8S-32x32 ABC data lines(Not working properly, multiple prints appear )

Please help me to set different scan rate. is there any other libraries has to downloaded or any other arguments i need to give.. ??

Sorry for posting in that issue i thought it was similar

**Comment by hzeller** [comment]
see https://github.com/hzeller/rpi-rgb-led-matrix/issues/390
