### ISSUE TITLE
-L (large display) option for ft-server

### ISSUE THREAD

**Issue by marcobrianza** [hzeller/flaschen-taschen#36]
Hello, and thank you for this great project.
I'm testing some configuration with Processing sending images to ft-server: it works :-)
I have seen that ft-server, differently from the other demos, is missing the -L option for U turn display configuration.
Is it a feature you can add ? 
Thank you
Marco

**Comment by hzeller** [comment]
I've updated the matrix library, so you can now use the [`--led-pixel-mapper="U-mapper"`](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#u-mapper)  feature.

**Comment by marcobrianza** [comment]
thank you!, I'll try it as soon as possible.
