### ISSUE TITLE
how to create own Image ppm file in flaschen -taschen

### ISSUE THREAD

**Issue by ManjunathRN** [hzeller/flaschen-taschen#38]
Hello sir,
I am new to git hub 
I'm working on HUB75 for a project with Pi, and i am using your client server code with 1:16s scan rate , HUB75 board each four 32x32 panel connected in series and parallel .I have did different  types of text scrolling and  yours  ppm files as included in this flaschen -taschen but i don't know how to create own ppm image file and run it in this F/T protocol .please help  me actually i am new one to this 
Thank you

**Comment by hzeller** [comment]
Please read the [protocol documentation](https://github.com/hzeller/flaschen-taschen/blob/master/doc/protocols.md#flaschen-taschen-protocol). The PPM format is the simplest image format essentially, just all the pixels in binary format one after another.

If you want to send images, just store them as PPM format in your favorite image editor.

If you want to get started programming things, you don't even need to assemble that yourself; you can use the [C++ API](https://github.com/hzeller/flaschen-taschen/tree/master/api/include) or [Python API](https://github.com/hzeller/flaschen-taschen/tree/master/api/python).
