### ISSUE TITLE
send-text: if text is '-', accept input from stdin

### ISSUE THREAD

**Issue by elimisteve** [hzeller/flaschen-taschen#50]
...just like `send-image` and `send-video`.

Then I can call `send-text` without trusting user input :smiley: .

**Comment by hzeller** [comment]
Well, unlike the other tools where `-` is interpreted as filename, here, `-` would be a proper text, so you would never be able to print a dash.

So we need to add a filename argument first:
We should have another flag that indicates reading from a filename. Unfortunately, we already have `-f`, which would be a good natural choice, but maybe `-i <filename>` ? (i for input).

Then, we either can have text directly on the command-line, if `-i` is not given or use it from the file. And  then, the filename can be `-` as well for stdin reading.

So synopsis would be
```
usage: ./send-text [options] [<TEXT>|-i <textfile>]
```

**Comment by elimisteve** [comment]
Sounds great to me :+1:

**Comment by elimisteve** [comment]
Do you think this will take long to add? I am trying to finish a Noisebridge project today that uses this feature.

Thanks.

**Comment by hzeller** [comment]
I can have a look at my commute this evening > 19:00.

**Comment by elimisteve** [comment]
@hzeller Perfect! Thank you.
