### ISSUE TITLE
Server error: Message too long in vout display flaschen

### ISSUE THREAD

**Issue by kirkas** [hzeller/flaschen-taschen#53]
Hi,

First of all, thank you so much for your work on flashen-tashen & rpi-rgb-led-matrix ! I've been experimenting with RPI and LED matrix for a couple months and all your work has saved me months (years!) of work :)

Second, I'm having some issues streaming to the RPI server from another computer.

**Context**: trying to send my square, 64x64 pixel video (`squarevideo.h264`) to the ft-server, built to output on a 64x64 LED matrix display.

I've managed to make it work when streaming the video from the RPI itself (i.e. run through an SSH console):

```
./send-video -g 64x64 home/pi/Library/picamerascript/squarevideo.h264
```

Now if I run the same command, but from my computer, I get this

```
./send-video -h raspberrypi.local -g 64x64 ~/rasberrypi/squarevideo.h264
flaschen vout display error: sendmsg: error Message too long in vout display flaschen
flaschen vout display error: sendmsg: error Message too long in vout display flaschen
flaschen vout display error: sendmsg: error Message too long in vout display flaschen
...
```

Interestingly, if I reduce the dimension to anything _below_ 56 it _does_ work 
```
./send-video -h raspberrypi.local -g 32x32 ~/rasberrypi/squarevideo.h264
./send-video -h raspberrypi.local -g 55x55 ~/rasberrypi/squarevideo.h264
```
^ these works, but `-g 56x56` will fail.

------
Setup
OSX: Software: Max OSX catalina 10.15.4 (19E287))
OSX: Terminal: ITerm3
Pi: Hardware: Raspberry Pi 4 Model B Rev 1.1
Pi: Software: Raspbian GNU/Linux 10 (buster)

**Comment by libschmudie-so** [comment]
I had the same issue. It seems MacOS limits UDP packages to 9216 bytes. You can use `sudo sysctl -w net.inet.udp.maxdgram=65535` to change this limit.

**Comment by kirkas** [comment]
oh dang - That worked :) Thank you so much!

**Comment by d3v-null** [comment]
it would be great if this were in the documentation somewhere!

**Comment by hzeller** [comment]
I've made the used UDP size configurable now and added a documentation about the OSX issue in https://github.com/hzeller/flaschen-taschen/tree/master/client#udp-size
