### ISSUE TITLE
Original rpi-rgb-led-matrix

### ISSUE THREAD

**Issue by hakao32** [hzeller/flaschen-taschen#56]
As I see, this flaschen-taschen uses uses old version of rpi-rgb-led-matrix repo. I tried to use latest rpi-rgb-led-matrix by copying in to server/rgb-matrix yet I got 
```main.cc:(.text.startup+0x11c): undefined reference to `rgb_matrix::CreateMatrixFromOptions(rgb_matrix::RGBMatrix::Options const&, rgb_matrix::RuntimeOptions const&)'```
How can I solve this?

**Comment by hzeller** [comment]
I've updated the repository to update to the latest version of the led matrix library. Can you try again ?
(probably easiest is to do a fresh recursive clone)

**Comment by hakao32** [comment]
Thank you :-) 
It worked :+1:
Yet once clone repo, rgb-matrix folder is empty. I cloned rpi-rgb-led-matrix to another folder and copied into rgb-matrix.
(tested with rpi4 and 32x32 rgb)
