### ISSUE TITLE
Streaming with VLC on large LED-Matrix

### ISSUE THREAD

**Issue by meikel-k** [hzeller/flaschen-taschen#57]
Hello ,
first,  thank you for the great work you have done with this fantastic apps.
I am running a project for our club to build several different LED-Matrix displays and most of all went fine and works.

Description and successful test of the size but slow: 

I do have one display with 4cols and 5rows of 64x32 led-displays.
- FT-Server runs with 256x160 on port 1337
- UDP buffer on the Pi's is increased to max.
- Using the flaschen-taschen client –> send-image, works fine.
- Using the flaschen-taschen client -> send-video works as well on the whole display size
   Command:   ./send-video -g256x160+0+0 -h <host> <video> , which is fine but very slow
- Using two Pi’s one for the matrix with the ft-server and the other to decode the video and send it over the network,  
   works better but still slow.
- Sending a webcam-stream with  command :  ./send-video -g256x160+0+0  http://<camera>  , 
   works fine .

Now the issue: 
I know that you did not wrote the vlc-client flaschen, perhaps you have an idea where to change to get it work. 

Using the VLC on a PC or running on a PI , the max size setup in the VLC Flaschen adapter which will work is width = 192 , height = 112.  
All other larger setup sizes result in black display no stream visible.

Wondering how Dirk in Schabeutz got his very large display working with stream showing.
Hope you have an idea or can help with this.

Kind regard

**Comment by hzeller** [comment]
I sent a patch a while back to vlc-devel that allows vlc to chunk the image to allow for large screens https://mailman.videolan.org/pipermail/vlc-devel/2020-March/132387.html

I was then getting busy to work on some technical stuff fighting some pandemic, so never got around to address the review comments. But it should be possible for you to just take this patch and make your copy of VLC work with it.

**Comment by meikel-k** [comment]
Hello Henner,
wow , thanks so much for the fast respond.

I have just downloaded the source code of VLC and made the patches in the flaschen.c.
Now fighting with my system to get the VLC with the changed file compiled and installed.

I will let you know after my success !

best regards
Michael

**Comment by meikel-k** [comment]
I belive this would be the same answer for the issue:  **Problem with --led-chain**  , raised by grthor on the 10Sept.

**Comment by meikel-k** [comment]
Hello Henner,

thanks again for you help.
It was really very hard staff to get a running system on Linux Mint ,  to be able to complie the VLC - player package.
Only missing packages , errors ...

At least I got one version running which gives me a compilation via Docker for a Windows System.
https://medium.com/@tobias.strg/compiling-vlc-3-x-in-2020-a390c6a73c24

I got now the latest Version of VLC 3.011.1

Made the patch you have send and compiled the VLC-package -> and now I am lucky to run a display with dimension (width x height) 256x160 pixels -  driven by VLC -Player

Very great stuff.

Thanks  a lot for your development .

I wil start now again to get a Linux running to be able to compile a Linux Version.
It will be better run on my slow laptop .

Best regards

Michael

**Comment by meikel-k** [comment]
Thanks again all works fine , now tryining to send to two different IP's , will see how I can get this work. The interface is already done

**Comment by win95c** [comment]
Hallo,
is there a possibility to expand the display to 256x192 pixels? (3x 64 Matrix)
Best regards
Frank

**Comment by meikel-k** [comment]
Hello Frank

with the patch supplied by Henner , VLC can now send larger images, as 
it split the image in several UDP pages each max filled.
So you can also run 256x192 pixel.

I was getting 256 x 160 , because the monitors I have build should be 
close to 16:9 resolution.
So I was using 4x Matrixmodules 64x32 in a line by 5 Matrixmodules in 
vertical ( 20 Displaymodules)
using Raspberry PI3 - B with a Shield for RGB-LED Matrix.

Kind regards
Michael


Am 23.03.2022 um 14:36 schrieb win95c:

**Comment by win95c** [comment]
Hi Michael,
Thank you for your prompt reply. I used the patch provided by Henner with VLC4.0. My display can do 256x192. There is always a black border of about 30 lines below. At first I suspected a hardware defect. I also swapped out the Raspberry+ Matrix. The error remains.
For me, this is the sign that the patch only works up to 256x160 pixels.
It doesn't work at all without a patch.
I am using Raspberry PI3 - B. The frame rate >55 Hz. 4 cols(64) x 3rows(64) pixel matrix.
The perspective should be 5 cols(64) x 3rows(64).

Maybe there are more users like where I can exchange ideas in German.

Best regards
Frank

**Comment by win95c** [comment]
Hello Henner,
you can look again over the patch of VLC Flaschen-taschen. The patch only works up to a maximum of 256x160 pixels. In addition, a black border of about 30 lines remains at 256x192.
In terms of hardware, I rule out a problem, because images or text work via led-image-viewer. The problem is still with the VLC. I used a self-made version of VLC4dev. I can't get any further at this point.
Best regards
Frank
