### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by mmartinortiz** [hzeller/flaschen-taschen#58]
Some weeks ago I bought a RGB Led Matrix, and during this last holidays I spent some days programming a video game for the matrix. Without your work, this could not be possible.

Thank you very much for enabling others :-)

PD: In case anyone is interested in putting to use their RGB Matrix: https://github.com/mmartinortiz/rgb-led-matrix-space-invaders

**Comment by hzeller** [comment]
Thanks for the feedback :)
Enjoy your new LED game goodness!
