### ISSUE TITLE
server Build fails for FT_BACKEND=rgb-matrix

### ISSUE THREAD

**Issue by erezlevanon** [hzeller/flaschen-taschen#64]
Hi, thanks for the useful libraries and utils this and rpi-rgb-led-matrix projects are great.

I'm trying to build the led matrix backend but the make command fails with 

```
~/flaschen-taschen/server/ $ sudo make FT_BACKEND=rgb-matrix
g++ -Wall -O3 -I../api/include -Irgb-matrix/include -DFT_BACKEND=1 -std=c++03 -c -o main.o main.cc
main.cc:42:12: fatal error: led-matrix.h: No such file or directory
   42 | #  include "led-matrix.h"
      |            ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: main.o] Error 1
```

I just cloned the repo so I'm not sure what might be causing the issue.

System: RPi Zero W
OS: Raspbian GNU/Linux 11 (bullseye)

I have [rpi-rgb-led-matrix](https://github.com/hzeller/rpi-rgb-led-matrix) cloned in the parent directory, and I've disabled some rpi functionallity based on recommendation from rpi-rgb-led-matrix/README.md, namely `sudo apt-get remove bluez bluez-firmware pi-bluetooth triggerhappy pigpio
`

**Comment by hzeller** [comment]
If you clone the repository with `--recursive`, it checks out the repo at the right place (which is actually `server/rgb-matrix`).

**Comment by hzeller** [comment]
Nit: best practice is to run `make` without sudo

**Comment by erezlevanon** [comment]
Solved, Thanks!

thanks for the make nit as well :)
